version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: myBlog
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myBlog
      MYSQL_USER: chan
      MYSQL_PASSWORD: chan
    ports:
      - "3306:3306"
    volumes:
      - myBlog-data:/var/lib/mysql

volumes:
  myBlog-data:

